# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode11.3
xcode_workspace: Angelo.xcworkspace
xcode_scheme: Angelo-Example
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max
before_install:
- gem install cocoapods
- cd Example
- pod install
